# Generated by Django 3.1.6 on 2021-03-06 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('facebook', models.CharField(max_length=256)),
                ('resolution', models.CharField(max_length=500, null=True)),
                ('format', models.CharField(max_length=60, null=True)),
                ('abs_path', models.CharField(max_length=500)),
                ('user_agent', models.CharField(max_length=256, null=True)),
                ('ip_addr', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
