# Generated by Django 3.1.6 on 2021-03-06 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbdl4u', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ip_addr',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_agent',
        ),
    ]
