# Generated by Django 3.1.6 on 2021-03-06 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbdl4u', '0006_auto_20210306_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='ip_addr',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user_agent',
        ),
    ]
